development:
  adapter: postgresql
  database: yawl-rails
  username: postgres

test:
  adapter: postgresql
  database: yawl-rails-test
  username: postgres


production:
  adapter: postgresql
  database: yawl-rails
  username: postgres
